spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
  security:
    user:
      name: admin
      password: secret

multi-tenancy:
  tenants:
    - tenantId: axon
      datasource:
        url: "jdbc:mysql://localhost:3306/axon"
        username: root
        password: secret
      flyway:
        url: ${multi-tenancy.tenants[0].datasource.url}
        user: ${multi-tenancy.tenants[0].datasource.username}
        password: ${multi-tenancy.tenants[0].datasource.password}
        enabled: true
        baseline-on-migrate: true
        locations:
          - "classpath:/db/migration/axon"
    - tenantId: projections
      datasource:
        url: "r2dbc:mysql://localhost:3306/projections"
        username: root
        password: secret
      flyway:
        url: "jdbc:mysql://localhost:3306/projections"
        user: ${multi-tenancy.tenants[1].datasource.username}
        password: ${multi-tenancy.tenants[1].datasource.password}
        enabled: false
        baseline-on-migrate: true
        locations:
          - "classpath:/db/migration/projections"

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
