spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
  webflux:
    base-path: "/api"

db:
  jdbc-base: "jdbc:mysql://localhost:3306"
  username: root
  password: secret

multi-tenancy:
  tenants:
    - tenantId: axon
      datasource:
        url: "${db.jdbc-base}/axon"
        username: ${db.username}
        password: ${db.password}
      flyway:
        enabled: true
        locations:
          - "classpath:/db/migration/axon"
    - tenantId: projections
      datasource:
        url: "${db.jdbc-base}/projections"
        username: ${db.username}
        password: ${db.password}
      flyway:
        enabled: true
        locations:
          - "classpath:/db/migration/projections"
    - tenantId: security
      datasource:
        url: "${db.jdbc-base}/security"
        username: ${db.username}
        password: ${db.password}
      flyway:
        enabled: true
        locations:
          - "classpath:/db/migration/security"


axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - mappings
