spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info
    nl.juraji: debug
    org.springframework.web: info
    org.springframework.security: info

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - mappings
