spring:
  datasource: # Default datasource is used for Axon
    url: "r2dbc:mysql://localhost:3306/axon"
    username: root
    password: secret
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:/db/migration/axon

projections:
  datasource:
    url: "r2dbc:mysql://localhost:3306/projections"
    username: root
    password: secret
  flyway:
    url: "jdbc:mysql://localhost:3306/projections"
    user: root
    password: secret
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:/db/migration/projections

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
