spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
  webflux:
    base-path: "/api"

db:
  host: "localhost"
  port: 3306
  username: root
  password: secret

multi-tenancy:
  tenants:
    - tenantId: axon
      datasource:
        url: "jdbc:mysql://${db.host}:${db.port}/axon"
        username: ${db.username}
        password: ${db.password}
      flyway:
        url: "jdbc:mysql://${db.host}:${db.port}/axon"
        user: ${db.username}
        password: ${db.password}
        enabled: true
        locations:
          - "classpath:/db/migration/axon"
    - tenantId: projections
      datasource:
        url: "r2dbc:mysql://${db.host}:${db.port}/projections"
        username: ${db.username}
        password: ${db.password}
      flyway:
        url: "jdbc:mysql://${db.host}:${db.port}/projections"
        user: ${db.username}
        password: ${db.password}
        enabled: true
        locations:
          - "classpath:/db/migration/projections"


axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - mappings
